### ISSUE TITLE
本番サーバー、デバックサーバーの motd が表示されていない

### ISSUE THREAD

**Issue by m1sk9** [GiganticMinecraft/seichi_infra#1092]
> Report by [kuroma6666](https://discord.com/channels/237758724121427969/1117430543378812978/1117430543378812978)

![image](https://github.com/GiganticMinecraft/seichi_infra/assets/82575685/b2e8c499-310f-441d-bf6c-65330fea1d5c)

発生自体はProxmox VEのアップデート後から発生しているが、 motdはbungeecordのプラグインで送出しているので疑うべきはbungeecordのレイヤが一番有力かも

なお、間にはTCPShieldもいる

**Comment by lis2a** [comment]
![image](https://github.com/GiganticMinecraft/seichi_infra/assets/82575685/81de08f4-d66a-41b0-952e-13b38d8784e2)

jms の banner もダメそう、うーむ

**Comment by m1sk9** [comment]
これは継続中

**Comment by Lucky3028** [comment]
SwiftMOTDというBungeecordプラグインで実現していますが、以下エラーで読み込まれていません。

```
[14:58:19 WARN]: Error loading plugin SwiftMOTD
java.lang.NoSuchMethodError: org.yaml.snakeyaml.representer.Representer: method 'void <init>()' not found
	at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.YamlRepresenter.<init>(YamlRepresenter.java:16) ~[?:?]
	at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.YamlConfiguration.<init>(YamlConfiguration.java:33) ~[?:?]
	at net.craftminecraft.bungee.bungeeyaml.bukkitapi.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:230) ~[?:?]
	at net.craftminecraft.bungee.bungeeyaml.pluginapi.ConfigurablePlugin.reloadConfig(ConfigurablePlugin.java:26) ~[?:?]
	at net.craftminecraft.bungee.bungeeyaml.pluginapi.ConfigurablePlugin.getConfig(ConfigurablePlugin.java:20) ~[?:?]
	at lv.bln.NettoHikari.SwiftMOTD.listeners.ServerListener.reloadConfiguration(ServerListener.java:32) ~[?:?]
	at lv.bln.NettoHikari.SwiftMOTD.listeners.ServerListener.<init>(ServerListener.java:27) ~[?:?]
	at lv.bln.NettoHikari.SwiftMOTD.SwiftMOTD.onLoading(SwiftMOTD.java:25) ~[?:?]
	at net.craftminecraft.bungee.bungeeyaml.pluginapi.ConfigurablePlugin.onLoad(ConfigurablePlugin.java:90) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:399) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:301) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:68) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.21-579.jar:git:Waterfall-Bootstrap:1.21-R0.1-SNAPSHOT:de8345a:579]
```

**Comment by Lucky3028** [comment]
[最終更新が11年前のプラグイン](https://www.spigotmc.org/resources/swiftmotd.221/history)なので、せめて数年以内に作成または更新されたプラグインへの切り替えまたは内製化が必要

**Comment by Lucky3028** [comment]
ざっと調べた感じ直近で更新があるのは https://github.com/obfuscatedgenerated/MagicMOTD とか？

**Comment by kory33** [comment]
プラグインの切り替えが必要というよりは、古いライブラリが依存に入っていてクラスパス上で衝突しているので、そのまま動かそうとすると class relocation が必要、というほうが正確そう

**Comment by Lucky3028** [comment]
ありがとうございます。
それはそれとして、メンテナンスされていないのは確かですし、OSSではなさそうなのでフォークしてメンテナンスするみたいなのもできないので、変えてしまったほうがはやくないですか？

**Comment by kory33** [comment]
それでいうと、変えてしまうか、実行直前に relocate するかの二択だとは思います

**Comment by m1sk9** [comment]
MagicMOTD への置き換えを実施

**Comment by m1sk9** [comment]
![Image](https://github.com/user-attachments/assets/dc72a2b9-4c1b-4075-b998-b994099fba67)

置き換えた (整えておきます)
